### ISSUE TITLE
RichText line break are not respected in inline element text

### ISSUE THREAD

**Issue by andrerom** [ezsystems/ezplatform-xmltext-fieldtype#34]
Probably mainly affects RichText field type, but tracking here as it affects migration scenario.

Original JIRA issue: ~~https://jira.ez.no/browse/EZP-23946~~ https://jira.ez.no/browse/EZP-23946

**Comment by vidarl** [comment]
The jira issue you refer to do not mention anything regarding line breaks...
cut&paste error ?

**Comment by andrerom** [comment]
@vidarl yes, search showed which one is should be (there are several): https://jira.ez.no/issues/?jql=text%20~%20%22RichText%20line%20break%22%20ORDER%20BY%20updated%20DESC%2C%20created%20DESC

**Comment by vidarl** [comment]
I assume you refere to [EZP-23946](https://jira.ez.no/browse/EZP-23946) but as stated there : 
> Note: XmlText does not support line breaks in inline element text, only in paragraph text. Since we aim to cover only existing XmlText capabilities in first release of RichText, this can be fixed after migration from XmlText is done.

So that issue is not related to ezxmltext -> richtext conversion.

It is not clear to me what kind of inline elements Petar is talking about, but that is a different story. For instance, emphasised text broken into multiple lines are indeed supported.

I guess this issue can be closed?

**Comment by andrerom** [comment]
Yes
